# Generated by Django 5.2.5 on 2025-08-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='temp_user', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
