# Generated by Django 5.0 on 2025-12-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Designates whether this user has been approved by an admin.'),
        ),
    ]
