# Generated by Django 5.2.5 on 2025-08-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('tournament', 'Tournament'), ('program', 'Program')], max_length=50)),
            ],
        ),
    ]
