# Generated by Django 5.2.5 on 2025-08-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_alter_teacherattendance_present'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_bim', models.TextField(default='ShankerDev Campus offers a Bachelor in Information Management (BIM) program.')),
                ('location', models.CharField(default='Kathmandu, Nepal', max_length=100)),
            ],
        ),
    ]
