# Generated by Django 5.2.5 on 2025-09-01 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_collegeinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedue',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_subjects',
            field=models.ManyToManyField(blank=True, to='campus.subject'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='semester',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('event', 'Event'), ('tournament', 'Tournament'), ('program', 'Program')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feedue',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feedue',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='attended_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='total_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('available_seats', models.PositiveIntegerField(default=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.faculty')),
            ],
        ),
    ]
