# Generated by Django 5.2.5 on 2025-09-02 14:17

# import django.db.models.deletion
# from django.conf import settings
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('campus', '0004_feedue_is_paid_studentprofile_current_subjects_and_more'),
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='course',
#             name='description',
#             field=models.CharField(default='No description available', max_length=500),
#             preserve_default=False,
#         ),
#         migrations.AddField(
#             model_name='course',
#             name='duration',
#             field=models.CharField(default='No Duration matched', max_length=50),
#             preserve_default=False,
#         ),
#         migrations.AddField(
#             model_name='course',
#             name='location',
#             field=models.CharField(default='Unknown location', max_length=200),
#             preserve_default=False,
#         ),
#         migrations.AlterField(
#             model_name='attendance',
#             name='date',
#             field=models.DateField(auto_now_add=True),
#         ),
#         migrations.AlterField(
#             model_name='attendance',
#             name='present',
#             field=models.BooleanField(default=True),
#         ),
#         migrations.AlterField(
#             model_name='attendance',
#             name='student',
#             field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to=settings.AUTH_USER_MODEL),
#         ),
#         migrations.AlterField(
#             model_name='attendance',
#             name='teacher',
#             field=models.ForeignKey(default='No attendance', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance', to=settings.AUTH_USER_MODEL),
#             preserve_default=False,
#         ),
#     ]




# Generated by Django 5.2.5 on 2025-09-02 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_feedue_is_paid_studentprofile_current_subjects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='No description available', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='No Duration matched', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(default='Unknown location', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance', to=settings.AUTH_USER_MODEL),
            # Removed default='No attendance' and preserve_default=False since ForeignKey defaults are typically handled by the database or require a valid ID
        ),
    ]