# Generated by Django 5.0 on 2025-12-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_remove_course_faculty_remove_feedue_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
