# Generated by Django 5.0 on 2025-12-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0010_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroutine',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='exam_routines/'),
        ),
    ]
