# Generated by Django 5.0 on 2025-12-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0011_examroutine_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
