# Generated by Django 5.0 on 2025-12-31 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0012_notification_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroutine',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title for the routine image', max_length=200),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.subject'),
        ),
    ]
