# Generated by Django 5.0 on 2025-12-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0013_examroutine_semester_examroutine_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroutine',
            name='end_date',
            field=models.DateField(blank=True, help_text='Exam ending date', null=True),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='start_date',
            field=models.DateField(blank=True, help_text='Exam starting date', null=True),
        ),
    ]
