# Generated by Django 6.0.2 on 2026-02-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0015_usernotificationtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationtracker',
            name='notification_type',
            field=models.CharField(choices=[('attendance', 'Attendance'), ('assignment', 'Assignment'), ('fee_reminder', 'Fee Reminder')], max_length=20),
        ),
    ]
